/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => Asn1HighlightPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var import_language = require("@codemirror/language");
var ASN1_KEYWORDS = /* @__PURE__ */ new Set([
  "BEGIN",
  "END",
  "DEFINITIONS",
  "IMPLICIT",
  "EXPLICIT",
  "OPTIONAL",
  "DEFAULT",
  "CHOICE",
  "SEQUENCE",
  "SET",
  "OF",
  "TAGS",
  "AUTOMATIC",
  "IMPORTS",
  "EXPORTS",
  "FROM",
  "TRUE",
  "FALSE",
  "NULL",
  "SIZE",
  "MIN",
  "MAX",
  "ABSENT",
  "PRESENT",
  "PLUS-INFINITY",
  "MINUS-INFINITY",
  "ALL",
  "EXCEPT",
  "UNION",
  "INTERSECTION",
  "CLASS",
  "TYPE-IDENTIFIER",
  "ABSTRACT-SYNTAX",
  "UNIVERSAL",
  "APPLICATION",
  "PRIVATE",
  "ENCODED",
  "CONSTRAINED",
  "INCLUDES",
  "PATTERN"
]);
var ASN1_BUILTIN_TYPES = /* @__PURE__ */ new Set([
  "INTEGER",
  "BOOLEAN",
  "ENUMERATED",
  "REAL",
  "NULL",
  "OCTET",
  "BIT",
  "IA5String",
  "UTF8String",
  "VisibleString",
  "NumericString",
  "PrintableString",
  "TeletexString",
  "VideotexString",
  "GraphicString",
  "GeneralString",
  "BMPString",
  "UniversalString",
  "OBJECT",
  "ObjectDescriptor",
  "UTCTime",
  "GeneralizedTime",
  "CHARACTER",
  "EMBEDDED",
  "EXTERNAL"
]);
function isBuiltinType(word) {
  return ASN1_BUILTIN_TYPES.has(word);
}
function isKeyword(word) {
  return ASN1_KEYWORDS.has(word);
}
var asn1Language = import_language.StreamLanguage.define({
  name: "asn1",
  startState: () => ({
    inBlockComment: false
  }),
  token: (stream, state) => {
    if (state.inBlockComment) {
      const next = stream.skipTo("*/");
      if (next !== false) {
        stream.next();
        stream.next();
        state.inBlockComment = false;
      } else {
        stream.skipToEnd();
      }
      return "comment";
    }
    if (stream.eatSpace())
      return null;
    if (stream.match("--")) {
      stream.skipToEnd();
      return "comment";
    }
    if (stream.match("/*")) {
      state.inBlockComment = true;
      const next = stream.skipTo("*/");
      if (next !== false) {
        stream.next();
        stream.next();
        state.inBlockComment = false;
      } else {
        stream.skipToEnd();
      }
      return "comment";
    }
    if (stream.match("::="))
      return "keyword";
    if (stream.match("..")) {
      if (stream.peek() === ".") {
        stream.match(".");
      }
      return "keyword";
    }
    if (stream.match(/^\[[0-9.]+]/))
      return "meta";
    if (stream.match(/^"[^"]*"/))
      return "string";
    if (stream.match(/^\b[0-9]+\b/))
      return "number";
    if (stream.match(/^[a-zA-Z][a-zA-Z0-9]*/)) {
      const word = stream.current();
      const upper = word.toUpperCase();
      if (upper === "OCTET" && stream.match(/^\s+STRING/))
        return "typeName";
      if (upper === "BIT" && stream.match(/^\s+STRING/))
        return "typeName";
      if (upper === "OBJECT" && stream.match(/^\s+IDENTIFIER/))
        return "typeName";
      if (upper === "CHARACTER" && stream.match(/^\s+STRING/))
        return "typeName";
      if (upper === "EMBEDDED" && stream.match(/^\s+PDV/))
        return "typeName";
      if (isKeyword(upper))
        return "keyword";
      if (isBuiltinType(upper))
        return "typeName";
      if (/^[A-Z]/.test(word))
        return "typeName";
      return "variableName";
    }
    if (stream.match(/^[,;]/))
      return "punctuation";
    stream.next();
    return null;
  },
  blankLine: (state) => {
    state.inBlockComment = false;
  }
});
var HIGHLIGHT_RULES = [
  // line comment
  {
    name: "cm-comment",
    test: (line, i) => {
      if (line[i] === "-" && line[i + 1] === "-") {
        return [line.length - i, line.slice(i)];
      }
      return null;
    }
  },
  // block comment
  {
    name: "cm-comment",
    test: (line, i) => {
      if (line[i] === "/" && line[i + 1] === "*") {
        const end = line.indexOf("*/", i + 2);
        if (end !== -1) {
          return [end + 2 - i, line.slice(i, end + 2)];
        }
        return [line.length - i, line.slice(i)];
      }
      return null;
    }
  },
  // tag [0], [1.2]
  {
    name: "cm-meta",
    test: (line, i) => {
      const m = line.slice(i).match(/^\[[0-9.]+]/);
      return m ? [m[0].length, m[0]] : null;
    }
  },
  // quoted string
  {
    name: "cm-string",
    test: (line, i) => {
      if (line[i] === '"') {
        const end = line.indexOf('"', i + 1);
        if (end !== -1)
          return [end + 1 - i, line.slice(i, end + 1)];
        return [line.length - i, line.slice(i)];
      }
      return null;
    }
  },
  // assignment ::=
  {
    name: "cm-keyword",
    test: (line, i) => {
      if (line.slice(i, i + 3) === "::=")
        return [3, "::="];
      return null;
    }
  },
  // range .. or ellipsis ...
  {
    name: "cm-keyword",
    test: (line, i) => {
      if (line[i] === "." && line[i + 1] === ".") {
        if (line[i + 2] === ".")
          return [3, "..."];
        return [2, ".."];
      }
      return null;
    }
  },
  // number
  {
    name: "cm-number",
    test: (line, i) => {
      if (/[0-9]/.test(line[i])) {
        const m = line.slice(i).match(/^[0-9]+/);
        return m ? [m[0].length, m[0]] : null;
      }
      return null;
    }
  },
  // word (keyword, type, field name)
  {
    name: "cm-word",
    test: (line, i) => {
      if (!/[a-zA-Z]/.test(line[i]))
        return null;
      const w = line.slice(i).match(/^[a-zA-Z][a-zA-Z0-9]*/);
      if (!w)
        return null;
      const word = w[0];
      const upper = word.toUpperCase();
      const rest = line.slice(i + word.length);
      if (upper === "OCTET" && /^\s+STRING/i.test(rest)) {
        const m = rest.match(/^(\s+STRING)/i);
        return [word.length + m[1].length, `OCTET${m[1]}`];
      }
      if (upper === "BIT" && /^\s+STRING/i.test(rest)) {
        const m = rest.match(/^(\s+STRING)/i);
        return [word.length + m[1].length, `BIT${m[1]}`];
      }
      if (upper === "OBJECT" && /^\s+IDENTIFIER/i.test(rest)) {
        const m = rest.match(/^(\s+IDENTIFIER)/i);
        return [word.length + m[1].length, `OBJECT${m[1]}`];
      }
      if (upper === "CHARACTER" && /^\s+STRING/i.test(rest)) {
        const m = rest.match(/^(\s+STRING)/i);
        return [word.length + m[1].length, `CHARACTER${m[1]}`];
      }
      if (upper === "EMBEDDED" && /^\s+PDV/i.test(rest)) {
        const m = rest.match(/^(\s+PDV)/i);
        return [word.length + m[1].length, `EMBEDDED${m[1]}`];
      }
      if (isKeyword(upper))
        return [word.length, word];
      if (isBuiltinType(upper))
        return [word.length, word];
      if (/^[A-Z]/.test(word))
        return [word.length, word];
      return [word.length, word];
    }
  },
  // punctuation
  {
    name: "cm-punctuation",
    test: (line, i) => {
      if (line[i] === "," || line[i] === ";")
        return [1, line[i]];
      return null;
    }
  }
];
function classifyWord(word) {
  const upper = word.toUpperCase();
  if (isKeyword(upper))
    return "keyword";
  if (isBuiltinType(upper))
    return "typeName";
  if (/^[A-Z]/.test(word))
    return "typeName";
  return "variableName";
}
function resolveColors() {
  const s = getComputedStyle(document.documentElement);
  const isDark = document.body.classList.contains("theme-dark");
  const g = (v, dark, light) => {
    const resolved = s.getPropertyValue(v).trim();
    return resolved || (isDark ? dark : light);
  };
  return {
    comment: g("--text-faint", "#888", "#888"),
    keyword: g("--text-accent", "#7cb7ff", "#4761c9"),
    typeName: g("--color-cyan", "#5eb8e6", "#1a6e8a"),
    number: g("--color-orange", "#e6a85e", "#b06d1a"),
    string: g("--color-green", "#6bb86b", "#3d8b3d"),
    meta: g("--text-muted", "#999", "#666"),
    variableName: g("--text-normal", "#ddd", "#333"),
    punctuation: g("--text-muted", "#999", "#666")
  };
}
var COLORS = {};
function renderHighlightedCode(code, codeEl) {
  const lines = code.split("\n");
  for (let li = 0; li < lines.length; li++) {
    const line = lines[li];
    let i = 0;
    while (i < line.length) {
      if (line[i] === " " || line[i] === "	") {
        let ws = "";
        while (i < line.length && (line[i] === " " || line[i] === "	")) {
          ws += line[i++];
        }
        codeEl.appendText(ws);
        continue;
      }
      let matched = false;
      for (const rule of HIGHLIGHT_RULES) {
        const result = rule.test(line, i);
        if (result) {
          const [len, text] = result;
          const type = rule.name === "cm-word" ? classifyWord(text) : rule.name.replace("cm-", "");
          const span = codeEl.createSpan();
          span.style.setProperty("color", COLORS[type] || "inherit", "important");
          span.appendText(text);
          i += len;
          matched = true;
          break;
        }
      }
      if (matched)
        continue;
      codeEl.appendText(line[i]);
      i++;
    }
    if (li < lines.length - 1) {
      codeEl.appendText("\n");
    }
  }
}
var Asn1HighlightPlugin = class extends import_obsidian.Plugin {
  async onload() {
    COLORS = resolveColors();
    this.registerEditorExtension(new import_language.LanguageSupport(asn1Language));
    const observer = new MutationObserver(() => {
      const all = document.querySelectorAll("code[class*='asn1']");
      for (let i = 0; i < all.length; i++) {
        const codeEl = all[i];
        if (codeEl.getAttribute("data-asn1-done"))
          continue;
        codeEl.setAttribute("data-asn1-done", "true");
        const source = codeEl.textContent || "";
        codeEl.empty();
        renderHighlightedCode(source, codeEl);
      }
    });
    observer.observe(document.body, { childList: true, subtree: true });
    this.register(() => observer.disconnect());
  }
};
